name: 'Secret Detection Test'

on:
  workflow_dispatch:

jobs:

  azure-client-secret-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Run Trivy in filesystem mode and scan for secrets'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          input: aquasecurity/trivy/pkg/fanal/secret/testdata
          ignore-unfixed: true
          security-checks: 'secret'
